### ISSUE TITLE
npm run start:pm2 Nuxt Auth地址不正确

### ISSUE THREAD

**Issue by d4renk** [kuizuo/chaoxing-sign#11]
执行npm run start:pm2 
Nuxt Auth地址是 http://localhost:8050/ 无法登录
执行pnpm run preview 则正常运行
系统
Debian GNU/Linux 10 x86_64
pnpm 7.13.5
Commits 4bfdb92457241c5365ec703f06c5b9ef3bfc9328

**Comment by kuizuo** [comment]
执行 pm2 log 输出的信息是什么？
是否有 pnpm build？是否有填写正确的 ecosystem.config.js 配置信息？
