### ISSUE TITLE
限制注册账号数量

### ISSUE THREAD

**Issue by d4renk** [kuizuo/chaoxing-sign#12]
希望可限制注册账号数量 避免被滥用
使用BasicAuth认证的话 会使登录变得繁琐

**Comment by kuizuo** [comment]
注册账号不想添加邮箱验证，因为账号的目的主要就是为了方便管理旗下的某星账号。

至于说滥用问题，公开地址肯定是存在的，哪怕是加了注册账号限制。

**Comment by kuizuo** [comment]
我这边教师账号是看不到签到的 IP，但事实上肯定都是同一个 IP（服务器 IP），想要规避的话上动态代理就不是很划算。毕竟某星还是没有什么风控的。

如果想为了保险，那肯定是自行部署最为方便了，或者是将其构建成 移动端应用用本机来签到是最为稳妥的。
