### ISSUE TITLE
如何收集隐私信息?

### ISSUE THREAD

**Issue by d4renk** [kuizuo/chaoxing-sign#13]
**隐私声明: 本应用会收集部分用户信息，用于优化应用体验，不会将数据用于任何途径，介意者请勿使用。**
收集信息的代码片段在哪
没找到在哪

**Comment by kuizuo** [comment]
因为需要通过一个账号来用于管理某星账号，这一部分就需要将其存入到数据库中（说难听点就是收集用户信息）。

本人确保不会将数据用于任何途径，也并不会在程序中添加诸如暗桩之类的操作。
