### ISSUE TITLE
登录xxt账号没有反应

### ISSUE THREAD

**Issue by ACSDSZ** [kuizuo/chaoxing-sign#17]
![屏幕截图 2023-09-06 195419](https://github.com/kuizuo/chaoxing-sign/assets/104259819/2cc8c076-5f6d-48d2-a126-c51edff00899)
这是因为我服务器是腾讯的被屏蔽的原因吗？

**Comment by kuizuo** [comment]
> ![屏幕截图 2023-09-06 195419](https://user-images.githubusercontent.com/104259819/265998473-2cc8c076-5f6d-48d2-a126-c51edff00899.png) 这是因为我服务器是腾讯的被屏蔽的原因吗？

尝试拉取一下最新代码，修复了一下账号退出问题。

**Comment by ACSDSZ** [comment]
> > ![屏幕截图 2023-09-06 195419](https://user-images.githubusercontent.com/104259819/265998473-2cc8c076-5f6d-48d2-a126-c51edff00899.png) 这是因为我服务器是腾讯的被屏蔽的原因吗？
> 
> 尝试拉取一下最新代码，修复了一下账号退出问题。

大佬我想问一下我是部署到docker上的我现在发现我在主页登录账号（前端的账号部署xxt）后他会直接跳转到http://localhost:8050是我那步搞错了吗

**Comment by kuizuo** [comment]
跳转到 http://localhost:8050
你可能需要将环境变量 更改一下

```.env
AUTH_ORIGIN="实际地址"
NEXTAUTH_URL="实际地址"
```

**Comment by ACSDSZ** [comment]
> 跳转到 http://localhost:8050 你可能需要将环境变量 更改一下
> 
> ```dotenv
> AUTH_ORIGIN="实际地址"
> NEXTAUTH_URL="实际地址"
> ```

是修改Dockerfile和env吗这两个我都修改了服务器重启了一边还是不管用依旧跳转本地

**Comment by kuizuo** [comment]
> 

你是用 edge 浏览器吗？你尝试换一下其他浏览器，或者清除一下缓存。

还有 nuxt-auth@0.6.0 版本有这个问题，我将版本降到了 0.5.0 了

**Comment by kuizuo** [comment]
> > > 
> > 
> > 
> > 你是用 edge 浏览器吗？你尝试换一下其他浏览器，或者清除一下缓存。
> > 还有 nuxt-auth@0.6.0 版本有这个问题，我将版本降到了 0.5.0 了
> 
> 换浏览器清缓存了也依旧跳本地

重新安装依赖呢？
能否提供演示视频？截图？

**Comment by ACSDSZ** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 你是用 edge 浏览器吗？你尝试换一下其他浏览器，或者清除一下缓存。
> > > > 还有 nuxt-auth@0.6.0 版本有这个问题，我将版本降到了 0.5.0 了
> > > 
> > > 
> > > 换浏览器清缓存了也依旧跳本地
> > 
> > 
> > 重新安装依赖呢？ 能否提供演示视频？截图？
> 
> [屏幕录制 2023-09-06 213155.zip](https://github.com/kuizuo/chaoxing-sign/files/12537845/2023-09-06.213155.zip)

两次跳转分别是点击了返回键和刷新

**Comment by kuizuo** [comment]
看样子你是用内网地址

你就需要将 实际地址替换成你的内网地址
AUTH_ORIGIN="实际地址"
NEXTAUTH_URL="实际地址"

**Comment by ACSDSZ** [comment]
> 看样子你是用服务器 IP地址
> 
> 你就需要将 环境变量中 AUTH_ORIGIN 与 NEXTAUTH_URL 替换成 实际地址，即你的服务器 IP AUTH_ORIGIN="实际地址" NEXTAUTH_URL="实际地址"
> 
> 如 xxx.xxx.xxx.xxx:8050
> 
> 不然链接中的 callbackUrl 不会是 localhost:8050 ![image](https://user-images.githubusercontent.com/61005888/266025913-945e8ddf-c68d-4326-83e2-417dd9825916.png)

![屏幕截图 2023-09-06 213852](https://github.com/kuizuo/chaoxing-sign/assets/104259819/62d52067-446e-4ac8-874a-7452eceef54f)
我修改过也还是那个地址之前就修改了服务器也重启了Dockerfile和env都修改了那个地方我手动改成真实ip是正常跳转的

**Comment by kuizuo** [comment]
> ![屏幕截图 2023-09-06 213852](https://user-images.githubusercontent.com/104259819/266026448-62d52067-446e-4ac8-874a-7452eceef54f.png) 我修改过也还是那个地址之前就修改了服务器也重启了Dockerfile和env都修改了那个地方我手动改成真实ip是正常跳转的

我猜测你可能修改了 Dockerfile，但是没有重新构建新的镜像。只是单纯重启容器，环境变量并不会生效。

**Comment by kuizuo** [comment]
> ![屏幕截图 2023-09-06 213852](https://user-images.githubusercontent.com/104259819/266026448-62d52067-446e-4ac8-874a-7452eceef54f.png) 我修改过也还是那个地址之前就修改了服务器也重启了Dockerfile和env都修改了那个地方我手动改成真实ip是正常跳转的

我猜测你可能修改了 Dockerfile，但是没有重新构建新的镜像。只是单纯重新容器，环境变量并不会生效

**Comment by ACSDSZ** [comment]
> > 显示这个是不是就是服务器ip被屏蔽了 如果是服务器ip被屏蔽我就部署到软路由上了
> 
> 能否打开控制台 网络面板看一下登录请求的响应内容？
> 
> 按理来说 只会输出 ”用户名或密码错误“ 或 ”登录成功” 这两个提示

![屏幕截图 2023-09-06 221753](https://github.com/kuizuo/chaoxing-sign/assets/104259819/85bd90ff-45de-4b3f-84fd-60a2c709729a)

**Comment by kuizuo** [comment]
> ![屏幕截图 2023-09-06 221753](https://user-images.githubusercontent.com/104259819/266039725-85bd90ff-45de-4b3f-84fd-60a2c709729a.png)

这或许需要你提供具体的账号给我进行测试，如果你不介意的话。

**Comment by ACSDSZ** [comment]
> > ![屏幕截图 2023-09-06 221753](https://user-images.githubusercontent.com/104259819/266039725-85bd90ff-45de-4b3f-84fd-60a2c709729a.png)
> 
> 这或许需要你提供具体的账号给我进行测试，如果你不介意的话。
> 
> 为了看下某星登录错误 输出的 errorMsg 值
> 
> ![image](https://user-images.githubusercontent.com/61005888/266041208-4982b2c9-eff3-44fd-a2e7-f8d95ccf3767.png)

密码输入错的也是返回这个 账号怎么给 给个联系方式发给你

**Comment by kuizuo** [comment]
> 密码输入错的也是返回这个 账号怎么给 给个联系方式发给你

邮箱: [hi@kuizuo.cn](mailto:hi@kuizuo.cn)

**Comment by 418667527** [comment]
我也是出现这样的   登录后提示 undefined

**Comment by kuizuo** [comment]
> 我也是出现这样的 登录后提示 undefined

那大概率是你的服务器有问题，你可以打开服务器的终端，输入 `curl https://www.chaoxing.com` 查看能否访问某星的服务器，如下图所示（正常）
<img width="1191" alt="image" src="https://github.com/kuizuo/chaoxing-sign/assets/61005888/b407b19a-0024-4d31-935b-b4487a65d870">

**Comment by 418667527** [comment]
我在win环境下搭建的 访问超星没问题

**Comment by kuizuo** [comment]
> 我在win环境下搭建的 访问超星没问题

那大概率就是你服务器无法访问某星了。

后续可能会考虑将本项目打包成桌面应用（Electron），这样只需要在本机打开应用即可。

**Comment by Memorz** [comment]
服务器是腾讯云的  curl某星服务器也正常    但登录帐号就会这样报错   是什么原因

> > 我在win环境下搭建的 访问超星没问题
> 
> 那大概率就是你服务器无法访问某星了。
> 
> 后续可能会考虑将本项目打包成桌面应用（Electron），这样只需要在本机打开应用即可。
