### ISSUE TITLE
Feat: 多个不同类型签到优化

### ISSUE THREAD

**Issue by SummonHIM** [kuizuo/chaoxing-sign#19]
当同时有多个不同类型的签到出现，如同时有二维码和手势签到。则二维码签到由于代码优
先执行会将其他类型签到挤掉。建议有多类型签到时，能重新唤起被挤掉的签到

还有一个是`/auth/login`登录后有时不会自动跳转回首页。大概率发生在直接访问`/auth/login`时

**Comment by kuizuo** [comment]
> 当同时有多个不同类型的签到出现，如同时有二维码和手势签到。则二维码签到由于代码优 先执行会将其他类型签到挤掉。建议有多类型签到时，能重新唤起被挤掉的签到

已添加签到成功过的活动任务不再返回置客户端。https://github.com/kuizuo/chaoxing-sign/commit/056a7129231a77838b21939b05721c6f1860a76b

但对于同时有多个签到任务还需多次点击一件签到，待优化。

**Comment by SummonHIM** [comment]
似乎docker环境下NUXT_IM_INIT_CONNECT并没有起作用。监听图标虽有显示但是后台并没有在监听

**Comment by kuizuo** [comment]
NUXT_IM_INIT_CONNECT 这个环境变量的作用就是 防止系统重启导致后台监听任务失效，设置为 true 则会在每次重启服务的时候，自动将数据库中处于监听状态的账号进行websocket连接

**Comment by SummonHIM** [comment]
> NUXT_IM_INIT_CONNECT 这个环境变量的作用就是 防止系统重启导致后台监听任务失效，设置为 true 则会在每次重启服务的时候，自动将数据库中处于监听状态的账号进行websocket连接

就是docker重启容器时没有自动恢复

**Comment by kuizuo** [comment]
Dockerfile 是否添加了  `ENV NUXT_IM_INIT_CONNECT=true`，添加后还需要重新构建镜像

**Comment by kuizuo** [comment]
> 我是编译后在容器里指定这个变量的

那不行，要么用 `ENV NUXT_IM_INIT_CONNECT=true`，要么启动的时候设置 `CMD ["NUXT_IM_INIT_CONNECT=true", "node", "/app/.output/server/index.mjs" ]`

 至于说为什么，这个估计根 nuxt [环境变量](https://nuxt.com/docs/guide/directory-structure/env) 有关
