### ISSUE TITLE
在监听模式下位置签到提示超出签到范围

### ISSUE THREAD

**Issue by 418667527** [kuizuo/chaoxing-sign#20]
在监听模式下位置签到提示超出签到范围，手动签到可以签到成功，是不是有其他地方设置位置信息？

**Comment by kuizuo** [comment]
位置签到你首先需要在设置页面中添加该账号的位置信息，注意经度和纬度的顺序，经纬度的获取地址 https://map.baidu.com

![image](https://github.com/kuizuo/chaoxing-sign/assets/61005888/04a3c863-79e3-4f71-a8ce-0bd32b65748d)

**Comment by 418667527** [comment]
![image](https://github.com/kuizuo/chaoxing-sign/assets/63603940/300aa1c5-74b7-43ce-867f-852a530a9301
已经设置了位置。同一个签到 监听提示超出范围，手动检测签到可以。经纬度设置没问题。

**Comment by 418667527** [comment]
![image](https://github.com/kuizuo/chaoxing-sign/assets/63603940/56319543-dfe5-4770-975e-fd6e5ec633ef)
已经设置了位置。
同一个签到 监听提示超出范围，手动检测签到可以。经纬度设置没问题。

**Comment by kuizuo** [comment]
> ![image](https://user-images.githubusercontent.com/63603940/267829693-56319543-dfe5-4770-975e-fd6e5ec633ef.png) 已经设置了位置。 同一个签到 监听提示超出范围，手动检测签到可以。经纬度设置没问题。

你在设置页面填写相关信息后，需要重新开始监听，否则监听任务的设置还是之前的。

<img width="527" alt="image" src="https://github.com/kuizuo/chaoxing-sign/assets/61005888/dbee74e8-65eb-480d-bf27-fd2439ff8182">

当然你可能会说为什么不在更新设置选项的，将监听任务的账号也同步更新设置。其原因是因为创建监听任务的时候，所获取的就是当前账号的信息，你所更改的设置信息将不会生效。

**Comment by 418667527** [comment]
已解决 谢谢大佬
