### ISSUE TITLE
关于自动签到

### ISSUE THREAD

**Issue by moxiaowk** [kuizuo/chaoxing-sign#22]
大佬有没有考虑优化一下自动签到，感觉有自动签到就更完美了

实现方式类似如下，利用IM协议监听

https://github.com/cxOrz/chaoxing-sign-cli/issues/50

**Comment by moxiaowk** [comment]
补充  https://github.com/cxOrz/chaoxing-sign-cli/blob/main/apps/server/src/monitor.ts

**Comment by kuizuo** [comment]
本方案就是 采用 IM 协议监听，你只需要点击监听按钮 即可开始监听。

![image](https://github.com/kuizuo/chaoxing-sign/assets/61005888/32c7d3b5-a7fe-464b-b542-e2ca8a5049c9)

**Comment by kuizuo** [comment]
> 本方案就是 采用 IM 协议监听，你只需要点击监听按钮 即可开始监听。
> 
> ![image](https://user-images.githubusercontent.com/61005888/268720162-32c7d3b5-a7fe-464b-b542-e2ca8a5049c9.png)

处于监听状态后，要确保网站服务不重启，否则会断开已建立的 Websocket 链接，因此可以在 .env 环境变量设置 `NUXT_IM_INIT_CONNECT=true` 表示重启服务器是否将监听账号重新建立连接。

**Comment by kuizuo** [comment]
比较可惜的是当时实现该功能为了就是能够让 除了二维码签到类型的签到任务能够自动完成，然而某星新增了签到检测，导致现在 签到码与手势签到 都需要对应的信息（签到码与手势轨迹）才能够真正成功签到，而多数老师都是采用这三种类型签到，因此在我现在看来自动签到的意义便不会特别大。

**Comment by moxiaowk** [comment]
好的谢谢大佬，但是实测好像没成功签到啊，如图普通签到
![Screenshot_2023-09-19-08-09-24-191_com chaoxing mobile](https://github.com/kuizuo/chaoxing-sign/assets/62387130/874368c1-e128-45d2-88e4-90a52a0e0800)
![Screenshot_2023-09-19-08-09-31-993_com android chrome-edit](https://github.com/kuizuo/chaoxing-sign/assets/62387130/0e12beb1-327d-4450-b32d-be0b154b0d8d)
![Screenshot_2023-09-19-08-10-31-362_com chaoxing mobile-edit](https://github.com/kuizuo/chaoxing-sign/assets/62387130/05f722dd-7b74-4091-81de-4a1164d460af)

**Comment by moxiaowk** [comment]
https://www.52pojie.cn/forum.php?mod=viewthread&tid=1827947&page=1#pid47912911

顺便分享一个大佬的分析日志

**Comment by kuizuo** [comment]
因此我的服务器没有设置 NUXT_IM_INIT_CONNECT ，因为内存开销会比较大，对于重启的一瞬间我未采取消息队列的形式不断连接（可能会导致连接失败）。

**Comment by kuizuo** [comment]
页面上的监听状态并不是真实，同步账号的时候并没有判断是否处于监听队列中，会在后续版本中针对监听状态进行一个优化。

目前来看还有一个小问题，就是在开启监听任务几小时后，**可能**会断开连接，具体原因还未知。
