### ISSUE TITLE
自动签到断连

### ISSUE THREAD

**Issue by moxiaowk** [kuizuo/chaoxing-sign#24]
大佬，之前我使用这个项目
https://github.com/cxOrz/chaoxing-sign-cli
时似乎没有出现断连的问题，大佬能不能借鉴一下他的实现方式，当时他是前后端分离然后后端用api调用的，使用时后端在screen里运行，然后自动签到可以稳定很久正常运行😍😍

具体实现的文件：https://github.com/cxOrz/chaoxing-sign-cli/blob/main/apps/server/src/monitor.ts

**Comment by syjuuxy** [comment]
你就是那个 微信小程序
柠宇云签吧标签😀
