### ISSUE TITLE
出现了：没有调用 WSAStartup，或者 WSAStartup 失败的问题

### ISSUE THREAD

**Issue by Respawn-ID** [kuizuo/chaoxing-sign#27]
如题，第一次部署带数据库的项目有点懵= =

**Comment by Respawn-ID** [comment]
C:\Users\Administrator\chaoxing-sign>npx prisma db push
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "aws-0-ap-northeast-2.pooler.supabase.com:6543"

Error: Schema engine error:
db error: ERROR: prepared statement "s0" does not exist

Error in PostgreSQL connection: Error { kind: Io, cause: Some(Os { code: 10093, kind: Uncategorized, message: "应用程序 没有调用 WSAStartup，或者 WSAStartup 失败。" }) }

**Comment by Respawn-ID** [comment]
`C:\Users\Administrator\chaoxing-sign>npx prisma db push
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "aws-0-ap-northeast-2.pooler.supabase.com:6543"

Error: Schema engine error:
db error: ERROR: prepared statement "s0" does not exist

Error in PostgreSQL connection: Error { kind: Io, cause: Some(Os { code: 10093, kind: Uncategorized, message: "应用程序 没有调用 WSAStartup，或者 WSAStartup 失败。" }) }`

**Comment by kuizuo** [comment]
这个问题貌似是 AWS 的服务所导致的，你可能需要查阅相关配置文档进行解决。

确保 .env 文件中的环境变量 DATABASE_URL 能够正常连接。

**Comment by Respawn-ID** [comment]
> 这个问题貌似是 AWS 的服务所导致的，你可能需要查阅相关配置文档进行解决。
> 
> 确保 .env 文件中的环境变量 DATABASE_URL 能够正常连接。

深感自己能力不够，还是不太会弄.....
