### ISSUE TITLE
如何设置监听间隔频率

### ISSUE THREAD

**Issue by TarikVon** [kuizuo/chaoxing-sign#29]
作者nb！这个项目非常的实用。
但是我有一个问题，每次监听功能的时间间隔有点长，我想缩短监听频率，我可以自定义吗

**Comment by kuizuo** [comment]
> 作者nb！这个项目非常的实用。 但是我有一个问题，每次监听功能的时间间隔有点长，我想缩短监听频率，我可以自定义吗

监听任务是通过easemob-websdk(websocket)实现的，因此其实并没有时间间隔这一说法，一有学习通的任务(通知)就会立刻监听到，只是取决于我们什么时候处理。

我在设置选项中添加了一项 签到延迟 就是为了反正监听到任务后，立马执行签到这一情况
