### ISSUE TITLE
位置签到validate错误

### ISSUE THREAD

**Issue by TarikVon** [kuizuo/chaoxing-sign#30]
如题，在我测试位置签到功能时，坐标设置正确，返回错误：课程: 测试 活动: 签到 [位置签到]结果: validate
在课程详情里提示的错误为：
Invalid `prisma.signLog.createMany()` invocation: { data: [ { id: "4000079911032_240133230", activityId: "4000079911032", isSigned: false, result: "不在可签到范围内", time: new Date("2023-11-22T01:15:03.921Z"), accountId: "240133230" }, { id: "4000079909989_240133230", activityId: "4000079909989", isSigned: false, result: "不在可签到范围内", time: new Date("2023-11-22T01:15:03.921Z"), accountId: "240133230" } ], skipDuplicates: true } Argument `activityName` is missing.
事实上，坐标定位的经纬度设置应该是没有错的。当我在手机上打开签到界面的时候，此时在服务器中进行位置签到操作，就能签到成功了；但是只要不打开就不能在服务器中签到。

**Comment by smile31768** [comment]
+1

**Comment by kuizuo** [comment]
重新抓包发现多了个参数，目前已修复 https://github.com/kuizuo/chaoxing-sign/commit/5a30a7ecfcc8ec854951596b7ae0476e73c1658a

**Comment by TarikVon** [comment]
经过在本地服务器和https://cx.kuizuo.cn/测试，仍然报了validate错误

**Comment by kuizuo** [comment]
see https://github.com/kuizuo/chaoxing-sign/issues/31#issuecomment-1822817105
