### ISSUE TITLE
大佬你好 我在vercel上部署了此项目，但是在连接数据库时遇到了问题，能否提供一个教程说一下怎么在vercel部署并且弄好数据库，谢谢大佬

### ISSUE THREAD

**Issue by maotuworkroom** [kuizuo/chaoxing-sign#40]
如题

**Comment by maotuworkroom** [comment]
我已经注册了supabase，并且填入了.env中可是还是注册不了账号

**Comment by kuizuo** [comment]
是否有相关报错信息与图片？

目前学习通更改了请求协议，可能需要重新抓包修改下代码才能够正常跑通项目。

**Comment by maotuworkroom** [comment]
> 是否有相关报错信息与图片？
> 
> 
> 
> 目前学习通更改了请求协议，可能需要重新抓包修改下代码才能够正常跑通项目。

![image](https://github.com/kuizuo/chaoxing-sign/assets/37393495/6d5357f5-7df0-4606-972e-29b7e20d6daf)

**Comment by maotuworkroom** [comment]
> 是否有相关报错信息与图片？
> 
> 
> 
> 目前学习通更改了请求协议，可能需要重新抓包修改下代码才能够正常跑通项目。

我的报错是在注册登录这个界面的😭😭😭

**Comment by kuizuo** [comment]
你项目貌似是部署在 Vercel 上，你还需要在 Vercel 上添加一下环境变量 ，在 Vercel 中点击你的项目，入口 Settings -> Environment Variables 在下方将 DATABASE_URL 添加进去。

**Comment by maotuworkroom** [comment]
需要包含数据库用户名和密码吗？

**Comment by maotuworkroom** [comment]
> 你项目貌似是部署在 Vercel 上，你还需要在 Vercel 上添加一下环境变量 ，在 Vercel 中点击你的项目，入口 Settings -> Environment Variables 在下方将 DATABASE_URL 添加进去。

需要包含数据库用户名和密码吗？

**Comment by maotuworkroom** [comment]
> 你项目貌似是部署在 Vercel 上，你还需要在 Vercel 上添加一下环境变量 ，在 Vercel 中点击你的项目，入口 Settings -> Environment Variables 在下方将 DATABASE_URL 添加进去。

![image](https://github.com/kuizuo/chaoxing-sign/assets/37393495/50d2bcee-8860-47a0-9624-51192e09ec26)

**Comment by maotuworkroom** [comment]
> 你项目貌似是部署在 Vercel 上，你还需要在 Vercel 上添加一下环境变量 ，在 Vercel 中点击你的项目，入口 Settings -> Environment Variables 在下方将 DATABASE_URL 添加进去。

填的和.env里面的数据库地址一样的格式然后变成报这个错了

**Comment by maotuworkroom** [comment]
> 你项目貌似是部署在 Vercel 上，你还需要在 Vercel 上添加一下环境变量 ，在 Vercel 中点击你的项目，入口 Settings -> Environment Variables 在下方将 DATABASE_URL 添加进去。

以及我想问下这个命令是给数据库执行吗还是在项目执行
运行如下命令用于同步数据库：

npx prisma db push
pnpm run dev

**Comment by kuizuo** [comment]
> > 你项目貌似是部署在 Vercel 上，你还需要在 Vercel 上添加一下环境变量 ，在 Vercel 中点击你的项目，入口 Settings -> Environment Variables 在下方将 DATABASE_URL 添加进去。
> 
> 以及我想问下这个命令是给数据库执行吗还是在项目执行，谢谢大佬 运行如下命令用于同步数据库：
> 
> npx prisma db push pnpm run dev

在项目中你先配置好环境变量，然后执行上述命令后，会将数据与结构同步到数据中

**Comment by maotuworkroom** [comment]
> > > 你项目貌似是部署在 Vercel 上，你还需要在 Vercel 上添加一下环境变量 ，在 Vercel 中点击你的项目，入口 Settings -> Environment Variables 在下方将 DATABASE_URL 添加进去。
> 
> > 
> 
> > 以及我想问下这个命令是给数据库执行吗还是在项目执行，谢谢大佬 运行如下命令用于同步数据库：
> 
> > 
> 
> > npx prisma db push pnpm run dev
> 
> 
> 
> 在项目中你先配置好环境变量，然后执行上述命令后，会将数据与结构同步到数据中

您说的执行上述命令是指deploy项目吗谢谢！

**Comment by maotuworkroom** [comment]
> > > 你项目貌似是部署在 Vercel 上，你还需要在 Vercel 上添加一下环境变量 ，在 Vercel 中点击你的项目，入口 Settings -> Environment Variables 在下方将 DATABASE_URL 添加进去。
> 
> > 
> 
> > 以及我想问下这个命令是给数据库执行吗还是在项目执行，谢谢大佬 运行如下命令用于同步数据库：
> 
> > 
> 
> > npx prisma db push pnpm run dev
> 
> 
> 
> 在项目中你先配置好环境变量，然后执行上述命令后，会将数据与结构同步到数据中

![image](https://github.com/kuizuo/chaoxing-sign/assets/37393495/eb549046-360a-4d38-a0a3-eb47399aefb5)

**Comment by maotuworkroom** [comment]
> > > 你项目貌似是部署在 Vercel 上，你还需要在 Vercel 上添加一下环境变量 ，在 Vercel 中点击你的项目，入口 Settings -> Environment Variables 在下方将 DATABASE_URL 添加进去。
> 
> > 
> 
> > 以及我想问下这个命令是给数据库执行吗还是在项目执行，谢谢大佬 运行如下命令用于同步数据库：
> 
> > 
> 
> > npx prisma db push pnpm run dev
> 
> 
> 
> 在项目中你先配置好环境变量，然后执行上述命令后，会将数据与结构同步到数据中

![image](https://github.com/kuizuo/chaoxing-sign/assets/37393495/f63db6df-79e9-4b90-9401-3b82cd06efed)
这是我数据库后台目前的状态

**Comment by maotuworkroom** [comment]
> 是否有相关报错信息与图片？
> 
> 
> 
> 目前学习通更改了请求协议，可能需要重新抓包修改下代码才能够正常跑通项目。

Invalid `prisma.user.findFirst()` invocation: The table `public.User` does not exist in the current database
这个报错怎么处理哇，谢谢大佬

**Comment by kuizuo** [comment]
> > 是否有相关报错信息与图片？
> > 目前学习通更改了请求协议，可能需要重新抓包修改下代码才能够正常跑通项目。
> 
> Invalid `prisma.user.findFirst()` invocation: The table `public.User` does not exist in the current database 这个报错怎么处理哇，谢谢大佬

你私聊我 wx 吧，微信号 kuizuo12，在上班信息回复可能不及时

**Comment by maotuworkroom** [comment]
> > > 是否有相关报错信息与图片？
> 
> > > 目前学习通更改了请求协议，可能需要重新抓包修改下代码才能够正常跑通项目。
> 
> > 
> 
> > Invalid `prisma.user.findFirst()` invocation: The table `public.User` does not exist in the current database 这个报错怎么处理哇，谢谢大佬
> 
> 
> 
> 你私聊我 wx 吧，微信号 kuizuo12，在上班信息回复可能不及时

感谢🙏🏻

**Comment by maotuworkroom** [comment]
> > > > 是否有相关报错信息与图片？
> > 
> > > > 目前学习通更改了请求协议，可能需要重新抓包修改下代码才能够正常跑通项目。
> > 
> > > 
> > 
> > > Invalid `prisma.user.findFirst()` invocation: The table `public.User` does not exist in the current database 这个报错怎么处理哇，谢谢大佬
> > 
> > 
> > 
> > 你私聊我 wx 吧，微信号 kuizuo12，在上班信息回复可能不及时
> 
> 感谢🙏🏻

已加
