### ISSUE TITLE
密码有特殊符号时登录失败

### ISSUE THREAD

**Issue by d4renk** [kuizuo/chaoxing-sign#9]
比如学习通设置密码<Os0aa(aaa
学习通官方版可以正常登录 而chaoxing-sign则提示登录失败

**Comment by kuizuo** [comment]
> 比如学习通设置密码<Os0aa(aaa 学习通官方版可以正常登录 而chaoxing-sign则提示登录失败

已修复 https://github.com/kuizuo/chaoxing-sign/commit/a4366700891314f957ede8b37873dd0fc928cda2
